modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "combatlog"
version = "${version}"
displayName = "CombatLog"
authors = "WildToastyMop"
description = '''
An attempt to prevent people from logging out while in combat with another player
'''
logoFile = "assets/combatlog/icon.png"

[[dependencies.combatlog]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.combatlog]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
